const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:4400,
        sale:20,
        review:18,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:3580,
        sale:7,
        review:154,
    },{
        src: './images/kurly_003.jpg',
        name: '[오뚜기] 진비빔면 4개입',
        summary: '매콤달콤 시원한 여름 별미',
        price:3980,
        sale:10,
        review:89,
    },
    {
        src: './images/kurly_004.jpg',
        name: '[청정원] 고메 함박스테이크',
        summary: '육즙 가득 정통 함박',
        price:6480,
        sale:15,
        review:47,
    },
    {
        src: './images/kurly_005.jpg',
        name: '[빙그레] 바나나맛 우유 6입',
        summary: '국민 간식의 정석',
        price:5280,
        sale:5,
        review:223,
    },
    {
        src: './images/kurly_006.jpg',
        name: '[농심] 포테토칩 오리지널 110g',
        summary: '바삭하고 담백한 감자칩',
        price:1980,
        sale:8,
        review:134,
    },
    {
        src: './images/kurly_007.jpg',
        name: '[풀무원] 얇은피 꽉찬속 만두 1kg',
        summary: '속이 꽉 찬 정통 만두',
        price:7280,
        sale:12,
        review:98,
    },
    {
        src: './images/kurly_008.jpg',
        name: '[팔도] 비락식혜 6캔',
        summary: '전통의 맛 그대로',
        price:4980,
        sale:10,
        review:51,
    },
    {
        src: './images/kurly_009.jpg',
        name: '[CJ] 햇반 컵반 불고기덮밥',
        summary: '간편한 한끼 식사',
        price:3480,
        sale:6,
        review:78,
    },
    {
        src: './images/kurly_010.jpg',
        name: '[베스킨라빈스] 엄마는 외계인 파인트',
        summary: '달콤한 초코와 견과류의 조화',
        price:8800,
        sale:20,
        review:162,
    },
    {
        src: './images/kurly_011.jpg',
        name: '[서울우유] 흰 우유 1L',
        summary: '신선한 국산 원유 100%',
        price:2580,
        sale:4,
        review:112,
    },
    {
        src: './images/kurly_012.jpg',
        name: '[빙그레] 메로나 멀티 8개입',
        summary: '시원한 멜론맛 아이스크림',
        price:6480,
        sale:9,
        review:74,
    }    
]